In [1]:
import pandas as pd
import numpy as np
import pickle
import seaborn as sns
import matplotlib.pyplot as plt

from pandas_profiling import ProfileReport
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import Ridge, Lasso, ElasticNet, RidgeCV, LassoCV, ElasticNetCV, LinearRegression
from sklearn.model_selection import train_test_split
import statsmodels.api as sm

%matplotlib inline

<ipython-input-1-9d8a402a3f22>:7: DeprecationWarning: `import pandas_profiling` is going to be deprecated by April 1st. Please use `import ydata_profiling` instead.
  from pandas_profiling import ProfileReport


In [4]:
df = pd.read_csv("database/Admission_Prediction.csv ")
df

Serial No.  GRE Score  TOEFL Score  University Rating  SOP  LOR  CGPA  \
0             1      337.0        118.0                4.0  4.5  4.5  9.65   
1             2      324.0        107.0                4.0  4.0  4.5  8.87   
2             3        NaN        104.0                3.0  3.0  3.5  8.00   
3             4      322.0        110.0                3.0  3.5  2.5  8.67   
4             5      314.0        103.0                2.0  2.0  3.0  8.21   
..          ...        ...          ...                ...  ...  ...   ...   
495         496      332.0        108.0                5.0  4.5  4.0  9.02   
496         497      337.0        117.0                5.0  5.0  5.0  9.87   
497         498      330.0        120.0                5.0  4.5  5.0  9.56   
498         499      312.0        103.0                4.0  4.0  5.0  8.43   
499         500      327.0        113.0                4.0  4.5  4.5  9.04   

     Research  Chance of Admit  
0           1             0.92  
1           1             0.76  
2           1             0.72  
3           1             0.80  
4           0             0.65  
..        ...              ...  
495         1             0.87  
496         1             0.96  
497         1             0.93  
498         0             0.73  
499         0             0.84  

[500 rows x 9 columns]

# Profile Report

In [3]:
pr = ProfileReport(df)
pr.to_widgets()

Summarize dataset:   0%|          | 0/5 [00:00<?, ?it/s]

Generate report structure:   0%|          | 0/1 [00:00<?, ?it/s]

Render widgets:   0%|          | 0/1 [00:00<?, ?it/s]


# Data Cleansing 

In [5]:
df["University Rating"].fillna(np.mean(df["University Rating"]),inplace=True)

In [6]:
df["GRE Score"].fillna(np.mean(df["GRE Score"]),inplace=True)

In [7]:
df["TOEFL Score"].fillna(np.mean(df["TOEFL Score"]),inplace=True)

In [8]:
df.drop(columns=["Serial No."],inplace=True)

In [11]:
df.describe()

GRE Score  TOEFL Score  University Rating         SOP        LOR  \
count  500.000000   500.000000         500.000000  500.000000  500.00000   
mean   316.558763   107.187755           3.121649    3.374000    3.48400   
std     11.103952     6.051338           1.128802    0.991004    0.92545   
min    290.000000    92.000000           1.000000    1.000000    1.00000   
25%    309.000000   103.000000           2.000000    2.500000    3.00000   
50%    316.558763   107.000000           3.000000    3.500000    3.50000   
75%    324.000000   112.000000           4.000000    4.000000    4.00000   
max    340.000000   120.000000           5.000000    5.000000    5.00000   

             CGPA    Research  Chance of Admit  
count  500.000000  500.000000        500.00000  
mean     8.576440    0.560000          0.72174  
std      0.604813    0.496884          0.14114  
min      6.800000    0.000000          0.34000  
25%      8.127500    0.000000          0.63000  
50%      8.560000    1.000000          0.72000  
75%      9.040000    1.000000          0.82000  
max      9.920000    1.000000          0.97000

## Linear Model

In [12]:
y = df[["Chance of Admit"]]
x = df.drop(columns=["Chance of Admit"])

In [13]:
x,y

(      GRE Score  TOEFL Score  University Rating  SOP  LOR  CGPA  Research
 0    337.000000        118.0                4.0  4.5  4.5  9.65         1
 1    324.000000        107.0                4.0  4.0  4.5  8.87         1
 2    316.558763        104.0                3.0  3.0  3.5  8.00         1
 3    322.000000        110.0                3.0  3.5  2.5  8.67         1
 4    314.000000        103.0                2.0  2.0  3.0  8.21         0
 ..          ...          ...                ...  ...  ...   ...       ...
 495  332.000000        108.0                5.0  4.5  4.0  9.02         1
 496  337.000000        117.0                5.0  5.0  5.0  9.87         1
 497  330.000000        120.0                5.0  4.5  5.0  9.56         1
 498  312.000000        103.0                4.0  4.0  5.0  8.43         0
 499  327.000000        113.0                4.0  4.5  4.5  9.04         0
 
 [500 rows x 7 columns],
      Chance of Admit
 0               0.92
 1               0.76
 2     

In [14]:
scaler = StandardScaler()

In [15]:
arr = scaler.fit_transform(x)

In [16]:
df = pd.DataFrame(arr)
df

0         1         2         3         4         5         6
0    1.842741e+00  1.788542  0.778906  1.137360  1.098944  1.776806  0.886405
1    6.708143e-01 -0.031058  0.778906  0.632315  1.098944  0.485859  0.886405
2    5.124333e-15 -0.527313 -0.107877 -0.377773  0.017306 -0.954043  0.886405
3    4.905178e-01  0.465197 -0.107877  0.127271 -1.064332  0.154847  0.886405
4   -2.306679e-01 -0.692731 -0.994659 -1.387862 -0.523513 -0.606480 -1.128152
..            ...       ...       ...       ...       ...       ...       ...
495  1.392000e+00  0.134360  1.665688  1.137360  0.558125  0.734118  0.886405
496  1.842741e+00  1.623124  1.665688  1.642404  1.639763  2.140919  0.886405
497  1.211704e+00  2.119379  1.665688  1.137360  1.639763  1.627851  0.886405
498 -4.109644e-01 -0.692731  0.778906  0.632315  1.639763 -0.242367 -1.128152
499  9.412590e-01  0.961451  0.778906  1.137360  1.098944  0.767220 -1.128152

[500 rows x 7 columns]

In [52]:
ProfileReport(df).to_widgets()

Summarize dataset:   0%|          | 0/5 [00:00<?, ?it/s]

Generate report structure:   0%|          | 0/1 [00:00<?, ?it/s]

Render widgets:   0%|          | 0/1 [00:00<?, ?it/s]

In [17]:
from statsmodels.stats.outliers_influence import variance_inflation_factor
vif_df = pd.DataFrame()

In [18]:
vif_df["vif"] = [variance_inflation_factor(arr,i) for i in range(arr.shape[1])]
vif_df["features"] = x.columns

In [19]:
x_train, x_test, y_train,y_test = train_test_split(arr,y,test_size=0.25,random_state = 10)

In [20]:
lr = LinearRegression()

In [21]:
lr.fit(x_train,y_train)

LinearRegression()

In [22]:
test = scaler.transform([[333,110,3.5,4.2,4.5,9.6,1]])

In [24]:
lr.predict(test)

array([[0.92127953]])

In [25]:
def adjusted_r2(x,y,p):
    r2 = lr.score(x,y)
    n = x.shape[0]
    return 1 - (1-r2)*(n-1)/(n-p-1)

adjusted_r2(x_test,y_test,6)

0.8021538269494892

In [26]:
lr.coef_, lr.intercept_

(array([[0.02437995, 0.01075991, 0.0042218 , 0.00640688, 0.01343201,
         0.07416127, 0.01162996]]),
 array([0.72267437]))

# Lasso 

In [28]:
lassocv = LassoCV(cv = 375, max_iter=2000000, normalize=True)
lassocv.fit(x_train,y_train)

c:\python38\lib\site-packages\sklearn\utils\validation.py:73: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)


LassoCV(cv=375, max_iter=2000000, normalize=True)

In [30]:
alpha = lassocv.alpha_

In [31]:
lasso = Lasso(alpha=alpha)
lasso.fit(x_train,y_train)

Lasso(alpha=6.5752856007508446e-06)

In [32]:
lasso.score(x_test,y_test)

0.8117246063539879

# Ridge

In [33]:
ridgecv = RidgeCV(alphas=np.random.uniform(0,10,50), cv = 10 , normalize=True)
ridgecv.fit(x_train,y_train)

RidgeCV(alphas=array([8.15816692, 0.91928251, 2.83508033, 6.10128476, 4.04769323,
       5.70598542, 3.43413256, 6.89926919, 6.33856763, 9.4076495 ,
       4.59390275, 7.14533563, 4.99144314, 6.1518839 , 1.25915131,
       7.34151037, 2.35308968, 8.61319368, 6.21796194, 8.944272  ,
       7.38994488, 5.63070913, 0.65401034, 6.14060678, 2.09823619,
       9.43755432, 7.3031569 , 7.5766911 , 8.68088418, 4.48006267,
       7.92927327, 0.61658448, 0.83701396, 7.37590772, 7.68608293,
       5.64089986, 5.8058933 , 7.56278672, 1.65539183, 8.97072443,
       9.30883574, 4.62707675, 8.93340376, 4.81385781, 6.09345398,
       7.79079381, 2.14346253, 8.06145668, 3.03083023, 3.38769204]),
        cv=10, normalize=True)

In [34]:
alpha = ridgecv.alpha_

In [36]:
ridge = Ridge(alpha=alpha)

In [37]:
ridge.fit(x_train,y_train)

Ridge(alpha=0.6165844808425913)

In [38]:
ridge.score(x_test,y_test)

0.811808449190368

# Elastic Net

In [39]:
encv = ElasticNetCV(alphas=None, cv = 10)

In [40]:
encv.fit(x_train,y_train)

c:\python38\lib\site-packages\sklearn\utils\validation.py:73: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)


ElasticNetCV(cv=10)

In [41]:
alpha, l1_ratio = encv.alpha_, encv.l1_ratio

In [43]:
en = ElasticNet(alpha=alpha,l1_ratio=l1_ratio)

In [44]:
en.fit(x_train,y_train)

ElasticNet(alpha=0.0002617717942861511)

In [45]:
en.score(x_test,y_test)


0.8116877645007671